name: divelogtest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  path_provider: ^2.0.0
  share_plus: ^12.0.0
  csv: ^6.0.0
  printing: ^5.0.0
  pdf: ^3.0.0
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^14.2.7
  sqflite: ^2.0.0
  path: ^1.0.0
  shared_preferences: ^2.0.0
  uuid: ^4.0.0
  intl: ^0.20.2
  firebase_core: ^4.3.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  sqflite_common_ffi: ^2.4.0+2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
